services:
  - type: web
    name: enyo-trade
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: MAIL_TO
        sync: false
      - key: PORT
        value: 10000
